name: CI

on:
  push:
    branches: [ "main" ]
    paths: ['README.md']

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change README.md
        run: | 
          n=$(grep -oP '(?<=\*)\d+(?=\*)' README.md)
          echo "$n"
      - name: Commit changes
        run: |
          git config user.name "Interreto"
          git config user.email "interreto@seznam.cz"
          git add README.md
          if git diff --cached --quiet; then
            echo "README.md is already up to date."
            exit 0
          fi
          git commit -m "Update README.md"
          git push origin HEAD:main
