name: CI

on:
  push:
    branches: [ "main" ]
    paths: ['README.md']

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git ...
        run: | 
          apt-get install git
          git config user.name "Interreto"
          git config user.email "interreto@seznam.cz"
      - name: Clone ...
        run: git clone git@github.com:interreto/do-it-again.git .
      - name: Change README.md
        run: | 
          n=$(grep -oP '\*\K\d+(?=\*)' README.md)
          new_n=$((n + 1))
          sed -i "s/\*${n}\*/\*${new_n}\*/" README.md
      - name: Commit changes
        run: |
          git add README.md
          if git diff --cached --quiet; then
            echo "README.md is already up to date."
            exit 0
          fi
          git commit -m "Update README.md"
          git push origin HEAD:main
